with open('k8s-deployment.yaml', 'w', encoding='utf-8') as f:
    f.write('apiVersion: apps/v1\n')
    f.write('kind: Deployment\n')
    f.write('metadata:\n')
    f.write('  name: ritham-farm-api\n')
    f.write('spec:\n')
    f.write('  replicas: 3\n')
    f.write('  selector:\n')
    f.write('    matchLabels:\n')
    f.write('      app: ritham-farm\n')
    f.write('  template:\n')
    f.write('    metadata:\n')
    f.write('      labels:\n')
    f.write('        app: ritham-farm\n')
    f.write('    spec:\n')
    f.write('      containers:\n')
    f.write('      - name: ritham-farm\n')
    f.write('        image: ritham-farm-api:latest\n')
    f.write('        imagePullPolicy: IfNotPresent\n')
    f.write('        ports:\n')
    f.write('        - containerPort: 5000\n')
    f.write('---\n')
    f.write('apiVersion: v1\n')
    f.write('kind: Service\n')
    f.write('metadata:\n')
    f.write('  name: ritham-farm-service\n')
    f.write('spec:\n')
    f.write('  selector:\n')
    f.write('    app: ritham-farm\n')
    f.write('  ports:\n')
    f.write('  - protocol: TCP\n')
    f.write('    port: 80\n')
    f.write('    targetPort: 5000\n')
    f.write('  type: LoadBalancer\n')
print('Done!')